name: 🚀 1. Deploy to Pro
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy to Pro
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer
        run: sudo apt-get update && sudo apt-get install -y composer

      - name: Validate Composer configuration
        run: composer validate

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist --verbose

      - name: Create .env file if missing
        run: |
          if [ ! -f ".env" ]; then
            echo "APP_NAME=Laravel" > .env
            echo "APP_ENV=local" >> .env
            echo "APP_KEY=" >> .env
            echo "APP_DEBUG=true" >> .env
            echo "APP_URL=http://localhost" >> .env
            echo "LOG_CHANNEL=stack" >> .env
            echo "LOG_DEPRECATIONS_CHANNEL=null" >> .env
            echo "LOG_LEVEL=debug" >> .env
            echo "" >> .env
            echo "# Database" >> .env
            echo "DB_CONNECTION=mysql" >> .env
            echo "DB_HOST=127.0.0.1" >> .env
            echo "DB_PORT=3306" >> .env
            echo "DB_DATABASE=laravel" >> .env
            echo "DB_USERNAME=root" >> .env
            echo "DB_PASSWORD=" >> .env
          fi

      - name: 📂 Sync files to Staging
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 109.106.251.30
          username: u442793684.architecturedesigning
          password: AAaa11@@AA@open2code.com
          server-dir: /
          exclude: |
            .env
